/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeadsChatRouteImport } from './routes/leads/chat'
import { Route as AdminChatRouteImport } from './routes/admin/chat'

const LeadsChatRoute = LeadsChatRouteImport.update({
  id: '/leads/chat',
  path: '/leads/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/admin/chat',
  path: '/admin/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/admin/chat': typeof AdminChatRoute
  '/leads/chat': typeof LeadsChatRoute
}
export interface FileRoutesByTo {
  '/admin/chat': typeof AdminChatRoute
  '/leads/chat': typeof LeadsChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin/chat': typeof AdminChatRoute
  '/leads/chat': typeof LeadsChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/admin/chat' | '/leads/chat'
  fileRoutesByTo: FileRoutesByTo
  to: '/admin/chat' | '/leads/chat'
  id: '__root__' | '/admin/chat' | '/leads/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminChatRoute: typeof AdminChatRoute
  LeadsChatRoute: typeof LeadsChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leads/chat': {
      id: '/leads/chat'
      path: '/leads/chat'
      fullPath: '/leads/chat'
      preLoaderRoute: typeof LeadsChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/admin/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AdminChatRoute: AdminChatRoute,
  LeadsChatRoute: LeadsChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
